# Dataset y Variable Objetivo

En esta sección se presenta el conjunto de datos utilizado en el proyecto y se define la variable objetivo del problema de clasificación.

El dataset corresponde a **Lending Club Loan Data (2007–2020)**, obtenido desde Kaggle. Este conjunto de datos contiene información de préstamos otorgados, incluyendo variables socioeconómicas, financieras, de crédito, empleo y propósito del préstamo.

Siguiendo la condición del proyecto, se trabajará con el **dataset completo**, sin realizar ningún tipo de muestreo, submuestreo o reducción arbitraria de filas.

El objetivo del proyecto es construir un modelo de clasificación supervisada que permita predecir si un préstamo termina en incumplimiento (**default**) o si es pagado completamente (**fully paid**).

Para esto primero se revisa la lectura del dataset, ajustando la ruta según sea necesaria:

In [13]:
import pandas as pd
from pathlib import Path
DATA_PATH = Path(r"C:\Users\Daniel Rangel\Documents\MachineLearning\Data\accepted_2007_to_2018Q4.csv.gz")

df = pd.read_csv(DATA_PATH, low_memory=False)

Para verificar la lectura de los datos usamos las funciones head() y tail() para ver las primeras y últimas filas del dataset.

In [10]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
2260696,88985880,NaN,40000.0,40000.0,40000.0,60 months,10.49,859.56,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260697,88224441,NaN,24000.0,24000.0,24000.0,60 months,14.49,564.56,C,C4,...,NaN,NaN,Cash,Y,Mar-2019,ACTIVE,Mar-2019,10000.0,44.82,1.0
2260698,88215728,NaN,14000.0,14000.0,14000.0,60 months,14.49,329.33,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260699,Total amount funded in policy code 1: 1465324575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260700,Total amount funded in policy code 2: 521953170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Definición de la variable objetivo

La variable objetivo del problema se construye a partir de la columna **loan_status**.

Se define la variable binaria **default** de la siguiente forma:

- **0 = Fully Paid**
- **1 = Charged Off**

Sin embargo, la columna **loan_status** contiene también otros estados intermedios como **Current**, **Late (31-120 days)** o **In Grace Period**. Estos estados no representan un desenlace final del préstamo, pero para el proposito de la evaluación de los modelos a usar, se tomarán en cuenta para el valor de **Fully paid**.


Después de esta categorización, se genera la variable **default**.

In [14]:
df["default"] = df["loan_status"].apply(lambda x: 1 if x == "Charged Off" else 0)

Podemos ver los resultados de la clasificación de la siguiente forma:

In [16]:
print("Distribución de la variable default:")
print(df["default"].value_counts(dropna=False))
print("Distribución porcentual de la variable default:")
print((df["default"].value_counts(normalize=True) * 100).round(2))
df[["loan_status", "default"]].head(15)

Distribución de la variable default:
0    1992142
1     268559
Name: default, dtype: int64
Distribución porcentual de la variable default:
0    88.12
1    11.88
Name: default, dtype: float64

    loan_status  default
0    Fully Paid        0
1    Fully Paid        0
2    Fully Paid        0
3       Current        0
4    Fully Paid        0
5    Fully Paid        0
6    Fully Paid        0
7    Fully Paid        0
8    Fully Paid        0
9    Fully Paid        0
10      Current        0
11      Current        0
12   Fully Paid        0
13  Charged Off        1
14   Fully Paid        0